- name: "Bug"
  description: "Something isn't working"
  color: "d73a4a"
- name: "Critical"
  description: "Immediate action required"
  color: "ffff00"
- name: "Docs"
  description: "Documentation improvements"
  color: "0075ca"
- name: "Feature"
  description: "Feature request"
  color: "73E25B"
- name: "Improvement"
  description: "Make something better"
  color: "6A1877"
