- name: "Bug"
  color: "d73a4a"
  description: "Something isn't working"
- name: "Critical"
  color: "ffff00"
  description: "Immediate action required"
- name: "Docs"
  color: "0075ca"
  description: "Documentation improvements"
- name: "Feature"
  color: "73E25B"
  description: "Feature request"
- name: "Improvement"
  color: "6A1877"
  description: "Make something better"
