name: Release

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - dev
    paths:
      - 'source/**'
      - 'package-lock.json'

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run tests
        run: npm i && npm test

      - name: Run features
        run: |
          if [ ${{ github.base_ref }} = main ]; then
            docker-compose up -d && npx cucumber-js --fail-fast --exit --format summary --publish-quiet
          else
            echo "Skipping features run on ${{ github.base_ref }}" 
          fi

      - name: Import GPG key
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.TOABOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.TOABOT_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Bump version
        run: |
          if [ ${{ github.base_ref }} = main ]; then
            npx lerna@6.5.1 version --conventional-graduate --no-commit-hooks --no-changelog --yes --message "chore(release): %s"
            git fetch
            git checkout dev
            git merge main
            git push --all origin --no-verify
          else
            npx lerna@6.5.1 version --conventional-prerelease --preid dev --no-commit-hooks --no-changelog --yes --message "chore(prerelease): %s" --git-tag-command "echo %s"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.TOABOT_GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: ${{ steps.gpg.outputs.name }}
          GIT_AUTHOR_EMAIL: ${{ steps.gpg.outputs.email }}
          GIT_COMMITTER_NAME: ${{ steps.gpg.outputs.name }}
          GIT_COMMITTER_EMAIL: ${{ steps.gpg.outputs.email }}

      - name: Publish packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          if [ ${{ github.base_ref }} = main ]; then
            npm publish
          else
            npm publish --tag dev
          fi
